name: Build the static site and push it to GitHub pages branch

on:
  push:
    branches: [ main ]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v4
    - name: Build site
      env: MAPTILER_KEY=${{ secrets.MAPTILER_KEY }}
      run: |
        npm install
        npm run build
        echo "www.jeff-horton.uk" > _site/CNAME
    - name: Push pages artifact
      uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
